Hw4
YuriKitt/NodeHW pull request #4
Opened 2023-11-01 19:20 UTC by YuriKitt

**Task:**
Test Setup:

- Set up a testing environment using Jest to write and run unit tests.
- Ensure that your project's dependencies include Jest and related testing libraries.

Unit Tests for APIs:

- Write unit tests for the API endpoints related to "Movies" and "Genres."
- Cover scenarios such as creating, reading, updating, and deleting movies and genres.
- Include tests for error handling and validation of input data.

Unit Tests for Movie Genre Search:

- Write unit tests for the movie genre search functionality.
- Test different genres and ensure that the API returns the expected results.
- Include edge cases and error scenarios in your tests.

Coverage and Reporting:

- Aim for high code coverage in your tests to ensure thorough testing of your application.
- Generate and include a code coverage report as part of your test results.

Documentation:

- Update your project's documentation to include information on running the tests using Jest.
- Provide clear instructions on how to run the tests and interpret the test results.

_Please review._

2023-12-07 17:34 UTC, IhorOsadchyi requested changes
As for me, using database for unit tests is not a right way. It's more like integration tests or even end-to-end. For unit testing you need to isolate function or method from 3-d party APIs using mock data. If you want, try to mock DB responses for testing purposes.

2023-12-10 15:46 UTC, YuriKitt commented
> As for me, using database for unit tests is not a right way. It's more like integration tests or even end-to-end. For unit testing you need to isolate function or method from 3-d party APIs using mock data. If you want, try to mock DB responses for testing purposes.

all mocked

2023-12-11 12:44 UTC, IhorOsadchyi commented on src/tests/genre.test.ts
> +});
There test cases are related to same endpoint so you can put them inside same describe block.

2023-12-11 12:44 UTC, IhorOsadchyi commented on src/tests/movie.test.ts
> +});
The same situation as above.

2023-12-11 14:48 UTC, YuriKitt commented on src/tests/genre.test.ts
> +});
resolved

2023-12-11 14:48 UTC, YuriKitt commented on src/tests/movie.test.ts
> +});
resolved

2023-12-11 16:49 UTC, IhorOsadchyi approved these changes

2023-12-11 16:54 UTC, merged